services:
  dev-cvc-client:
    container_name: dev-cvc-client
    networks:
      - host-bridge
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile.client
    ports:
      - 5173:5173
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: ./apps/client
          target: /usr/src/app/client
          ignore:
            - node_modules
        - action: rebuild
          path: ./apps/client/package.json
    depends_on:
      - dev-auvo-core-api
  cvc-db:
    container_name: cvc-db
    image: postgres:15.4-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  dev-cvc-server:
    networks:
      - host-bridge
    container_name: dev-cvc-server
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile.core-api
    ports:
      - 1209:1209
    develop:
      watch:
        - action: sync
          path: ./apps/server
          target: /usr/src/app/core-api
          ignore:
            - node_modules
        - action: rebuild
          path: ./apps/server/package.json
    env_file:
      - .env

networks:
  host-bridge:
    driver: bridge
